import { User } from "@/types/user";

const today = new Date();

export const testusers: User[] = [
  {
    id: 1,
    slug: `Frontend Roadmap`,
    name: `Denis`,
    email: `denispiyack@gmail.com`,
    accessTokenHash: `asdasdasdassfasf`,
    emailReportsEnabled: true,
    timezone: `UTC`,
    createdAt: today,
    updatedAt: today,
    progress: {
      javascript: { learned: 32, total: 40 },
      react: { learned: 18, total: 30 },
      browser: { learned: 12, total: 20 },
    },
  },
  {
    id: 2,
    slug: `Backend Architecture`,
    name: `Alex`,
    email: `alexdev@gmail.com`,
    accessTokenHash: `xczxczxcz123`,
    emailReportsEnabled: false,
    timezone: `Europe/Prague`,
    createdAt: today,
    updatedAt: today,
    progress: {
      javascript: { learned: 20, total: 40 },
      react: { learned: 6, total: 30 },
      browser: { learned: 15, total: 20 },
    },
  },
  {
    id: 3,
    slug: `UI Design System`,
    name: `Maria`,
    email: `maria.ui@gmail.com`,
    accessTokenHash: `qweqweqwe456`,
    emailReportsEnabled: true,
    timezone: `Europe/Warsaw`,
    createdAt: today,
    updatedAt: today,
    progress: {
      javascript: { learned: 14, total: 40 },
      react: { learned: 22, total: 30 },
      browser: { learned: 8, total: 20 },
    },
  },
  {
    id: 4,
    slug: `Mobile App Tasks`,
    name: `John`,
    email: `johnmobile@gmail.com`,
    accessTokenHash: `mobiletoken789`,
    emailReportsEnabled: true,
    timezone: `America/New_York`,
    createdAt: today,
    updatedAt: today,
    progress: {
      javascript: { learned: 40, total: 40 },
      react: { learned: 27, total: 30 },
      browser: { learned: 19, total: 20 },
    },
  },
  {
    id: 5,
    slug: `DevOps Monitoring`,
    name: `Sophie`,
    email: `sophie.ops@gmail.com`,
    accessTokenHash: `opssecuretoken`,
    emailReportsEnabled: false,
    timezone: `Asia/Tokyo`,
    createdAt: today,
    updatedAt: today,
    progress: {
      javascript: { learned: 5, total: 40 },
      react: { learned: 2, total: 30 },
      browser: { learned: 4, total: 20 },
    },
  },
];
